// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5GT6nVB5WgvLWb2iBXTk1E
// Component: 9pj4k2Np_V6
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_project5162.module.css"; // plasmic-import: 5GT6nVB5WgvLWb2iBXTk1E/projectcss
import sty from "./PlasmicWalletstatusvtwo.module.css"; // plasmic-import: 9pj4k2Np_V6/css

export const PlasmicWalletstatusvtwo__VariantProps = new Array(
  "disconnected",
  "connected"
);

export const PlasmicWalletstatusvtwo__ArgProps = new Array("walletaddress");

function PlasmicWalletstatusvtwo__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return true ? (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(projectcss.all, projectcss.root_reset, sty.root)}
    >
      {(hasVariant(variants, "disconnected", "disconnected") ? true : true) ? (
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__lkiLs,
            {
              [sty.text__disconnected__lkiLs1GkX2]: hasVariant(
                variants,
                "disconnected",
                "disconnected"
              )
            }
          )}
        >
          {"----"}
        </div>
      ) : null}

      <div
        className={classNames(projectcss.all, sty.freeBox__leRn6, {
          [sty.freeBox__connected__leRn679B8G]: hasVariant(
            variants,
            "connected",
            "connected"
          )
        })}
      >
        {(
          hasVariant(variants, "disconnected", "disconnected") ? false : true
        ) ? (
          <div
            className={classNames(projectcss.all, sty.freeBox__ufce3, {
              [sty.freeBox__connected__ufce379B8G]: hasVariant(
                variants,
                "connected",
                "connected"
              ),

              [sty.freeBox__disconnected__ufce31GkX2]: hasVariant(
                variants,
                "disconnected",
                "disconnected"
              )
            })}
          >
            {(
              hasVariant(variants, "disconnected", "disconnected")
                ? false
                : true
            )
              ? p.renderPlasmicSlot({
                  defaultContents: "0xB545A207759a397b5A4e24AF020DaBF619C7d809",
                  value: args.walletaddress,
                  className: classNames(sty.slotTargetWalletaddress, {
                    [sty.slotTargetWalletaddress__connected]: hasVariant(
                      variants,
                      "connected",
                      "connected"
                    ),

                    [sty.slotTargetWalletaddress__disconnected]: hasVariant(
                      variants,
                      "disconnected",
                      "disconnected"
                    )
                  })
                })
              : null}
          </div>
        ) : null}

        <div className={classNames(projectcss.all, sty.freeBox___5CJn9)} />

        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__lkPtr,
            {
              [sty.text__connected__lkPtr79B8G]: hasVariant(
                variants,
                "connected",
                "connected"
              ),

              [sty.text__disconnected__lkPtr1GkX2]: hasVariant(
                variants,
                "disconnected",
                "disconnected"
              )
            }
          )}
        >
          {hasVariant(variants, "connected", "connected")
            ? "Wallet Connected"
            : "Wallet Disconnected"}
        </div>
      </div>
    </div>
  ) : null;
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicWalletstatusvtwo__ArgProps,
      internalVariantPropNames: PlasmicWalletstatusvtwo__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicWalletstatusvtwo__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicWalletstatusvtwo";
  } else {
    func.displayName = `PlasmicWalletstatusvtwo.${nodeName}`;
  }
  return func;
}

export const PlasmicWalletstatusvtwo = Object.assign(
  // Top-level PlasmicWalletstatusvtwo renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicWalletstatusvtwo
    internalVariantProps: PlasmicWalletstatusvtwo__VariantProps,
    internalArgProps: PlasmicWalletstatusvtwo__ArgProps
  }
);

export default PlasmicWalletstatusvtwo;
/* prettier-ignore-end */
