// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5GT6nVB5WgvLWb2iBXTk1E
// Component: mUo8dNu01S5
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import ButtonB from "../../ButtonB"; // plasmic-import: oSXCQ8ez26/component
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_project_5162.module.css"; // plasmic-import: 5GT6nVB5WgvLWb2iBXTk1E/projectcss
import sty from "./PlasmicInvoicegeneration.module.css"; // plasmic-import: mUo8dNu01S5/css

export const PlasmicInvoicegeneration__VariantProps = new Array(
  "displayinvoice"
);

export const PlasmicInvoicegeneration__ArgProps = new Array(
  "date",
  "value",
  "awbbl",
  "qty",
  "gross",
  "volume",
  "invoiceno",
  "eta"
);

function PlasmicInvoicegeneration__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(projectcss.all, projectcss.root_reset, sty.root)}
    >
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__uQgei,
          {
            [sty.text__displayinvoice__uQgeIokUjk]: hasVariant(
              variants,
              "displayinvoice",
              "displayinvoice"
            )
          }
        )}
      >
        {hasVariant(variants, "displayinvoice", "displayinvoice")
          ? "INVOICE GENERATION"
          : "SALES ORDER GENERATION"}
      </div>

      <div
        data-plasmic-name={"applicationForm"}
        data-plasmic-override={overrides.applicationForm}
        className={classNames(projectcss.all, sty.applicationForm, {
          [sty.applicationForm__displayinvoice]: hasVariant(
            variants,
            "displayinvoice",
            "displayinvoice"
          )
        })}
      >
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox___8MuRw, {
            [sty.freeBox__displayinvoice___8MuRWokUjk]: hasVariant(
              variants,
              "displayinvoice",
              "displayinvoice"
            )
          })}
        >
          <div
            className={classNames(projectcss.all, sty.freeBox__vKagz, {
              [sty.freeBox__displayinvoice__vKagZokUjk]: hasVariant(
                variants,
                "displayinvoice",
                "displayinvoice"
              )
            })}
          >
            <div
              className={classNames(projectcss.all, sty.freeBox__cMQnQ, {
                [sty.freeBox__displayinvoice__cMQnQokUjk]: hasVariant(
                  variants,
                  "displayinvoice",
                  "displayinvoice"
                )
              })}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ctBq8,
                  {
                    [sty.text__displayinvoice__ctBq8OkUjk]: hasVariant(
                      variants,
                      "displayinvoice",
                      "displayinvoice"
                    )
                  }
                )}
              >
                {hasVariant(variants, "displayinvoice", "displayinvoice")
                  ? "Invoice No"
                  : "Order ID"}
              </div>

              {true ? (
                <div
                  className={classNames(projectcss.all, sty.freeBox__lSfPp, {
                    [sty.freeBox__displayinvoice__lSfPpokUjk]: hasVariant(
                      variants,
                      "displayinvoice",
                      "displayinvoice"
                    )
                  })}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__l34Dd
                    )}
                  >
                    {"#"}
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__ayPnk, {
                      [sty.freeBox__displayinvoice__ayPnKokUjk]: hasVariant(
                        variants,
                        "displayinvoice",
                        "displayinvoice"
                      )
                    })}
                  >
                    {p.renderPlasmicSlot({
                      defaultContents: "ABC123",
                      value: args.invoiceno,
                      className: classNames(sty.slotTargetInvoiceno, {
                        [sty.slotTargetInvoiceno__displayinvoice]: hasVariant(
                          variants,
                          "displayinvoice",
                          "displayinvoice"
                        )
                      })
                    })}
                  </div>
                </div>
              ) : null}
            </div>
          </div>

          {(
            hasVariant(variants, "displayinvoice", "displayinvoice")
              ? true
              : false
          ) ? (
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__gk6W, {
                [sty.freeBox__displayinvoice__gk6WOkUjk]: hasVariant(
                  variants,
                  "displayinvoice",
                  "displayinvoice"
                )
              })}
            >
              {(
                hasVariant(variants, "displayinvoice", "displayinvoice")
                  ? true
                  : true
              ) ? (
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___1D6HD,
                    {
                      [sty.text__displayinvoice___1D6HDokUjk]: hasVariant(
                        variants,
                        "displayinvoice",
                        "displayinvoice"
                      )
                    }
                  )}
                >
                  {"Order To: "}
                </div>
              ) : null}
              {(
                hasVariant(variants, "displayinvoice", "displayinvoice")
                  ? true
                  : true
              ) ? (
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__wGxCl,
                    {
                      [sty.text__displayinvoice__wGxClokUjk]: hasVariant(
                        variants,
                        "displayinvoice",
                        "displayinvoice"
                      )
                    }
                  )}
                >
                  {"Ship To:"}
                </div>
              ) : null}
            </p.Stack>
          ) : null}
          {(
            hasVariant(variants, "displayinvoice", "displayinvoice")
              ? true
              : true
          ) ? (
            <div
              className={classNames(projectcss.all, sty.freeBox__m6SfG, {
                [sty.freeBox__displayinvoice__m6SfGokUjk]: hasVariant(
                  variants,
                  "displayinvoice",
                  "displayinvoice"
                )
              })}
            >
              <div
                className={classNames(projectcss.all, sty.freeBox__c0DkA, {
                  [sty.freeBox__displayinvoice__c0DkAokUjk]: hasVariant(
                    variants,
                    "displayinvoice",
                    "displayinvoice"
                  )
                })}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__x4XRu,
                    {
                      [sty.text__displayinvoice__x4XRuokUjk]: hasVariant(
                        variants,
                        "displayinvoice",
                        "displayinvoice"
                      )
                    }
                  )}
                >
                  {"Invoice Date"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__otYjX,
                    {
                      [sty.text__displayinvoice__otYjXokUjk]: hasVariant(
                        variants,
                        "displayinvoice",
                        "displayinvoice"
                      )
                    }
                  )}
                >
                  {":"}
                </div>

                <div
                  data-plasmic-name={"supplier"}
                  data-plasmic-override={overrides.supplier}
                  className={classNames(projectcss.all, sty.supplier, {
                    [sty.supplier__displayinvoice]: hasVariant(
                      variants,
                      "displayinvoice",
                      "displayinvoice"
                    )
                  })}
                >
                  {p.renderPlasmicSlot({
                    defaultContents: "N/A",
                    value: args.date,
                    className: classNames(sty.slotTargetDate, {
                      [sty.slotTargetDate__displayinvoice]: hasVariant(
                        variants,
                        "displayinvoice",
                        "displayinvoice"
                      )
                    })
                  })}
                </div>
              </div>

              <div
                className={classNames(projectcss.all, sty.freeBox___0PtkT, {
                  [sty.freeBox__displayinvoice___0PtkTokUjk]: hasVariant(
                    variants,
                    "displayinvoice",
                    "displayinvoice"
                  )
                })}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__nZbnm,
                    {
                      [sty.text__displayinvoice__nZbnmokUjk]: hasVariant(
                        variants,
                        "displayinvoice",
                        "displayinvoice"
                      )
                    }
                  )}
                >
                  {"Invoice Value"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__y9Ssp,
                    {
                      [sty.text__displayinvoice__y9SspokUjk]: hasVariant(
                        variants,
                        "displayinvoice",
                        "displayinvoice"
                      )
                    }
                  )}
                >
                  {":"}
                </div>

                <div
                  data-plasmic-name={"shipmentmode"}
                  data-plasmic-override={overrides.shipmentmode}
                  className={classNames(projectcss.all, sty.shipmentmode, {
                    [sty.shipmentmode__displayinvoice]: hasVariant(
                      variants,
                      "displayinvoice",
                      "displayinvoice"
                    )
                  })}
                >
                  {p.renderPlasmicSlot({
                    defaultContents: "N/A",
                    value: args.value,
                    className: classNames(sty.slotTargetValue, {
                      [sty.slotTargetValue__displayinvoice]: hasVariant(
                        variants,
                        "displayinvoice",
                        "displayinvoice"
                      )
                    })
                  })}
                </div>
              </div>

              <div
                className={classNames(projectcss.all, sty.freeBox__mnWRo, {
                  [sty.freeBox__displayinvoice__mnWRookUjk]: hasVariant(
                    variants,
                    "displayinvoice",
                    "displayinvoice"
                  )
                })}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___1AalI,
                    {
                      [sty.text__displayinvoice___1AalIokUjk]: hasVariant(
                        variants,
                        "displayinvoice",
                        "displayinvoice"
                      )
                    }
                  )}
                >
                  {"AWB_BL No"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__gfUpE,
                    {
                      [sty.text__displayinvoice__gfUpEokUjk]: hasVariant(
                        variants,
                        "displayinvoice",
                        "displayinvoice"
                      )
                    }
                  )}
                >
                  {":"}
                </div>

                <div
                  data-plasmic-name={"origincountry"}
                  data-plasmic-override={overrides.origincountry}
                  className={classNames(projectcss.all, sty.origincountry, {
                    [sty.origincountry__displayinvoice]: hasVariant(
                      variants,
                      "displayinvoice",
                      "displayinvoice"
                    )
                  })}
                >
                  {p.renderPlasmicSlot({
                    defaultContents: "N/A",
                    value: args.awbbl,
                    className: classNames(sty.slotTargetAwbbl, {
                      [sty.slotTargetAwbbl__displayinvoice]: hasVariant(
                        variants,
                        "displayinvoice",
                        "displayinvoice"
                      )
                    })
                  })}
                </div>
              </div>

              <div
                className={classNames(projectcss.all, sty.freeBox__khcv, {
                  [sty.freeBox__displayinvoice__khcvOkUjk]: hasVariant(
                    variants,
                    "displayinvoice",
                    "displayinvoice"
                  )
                })}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___2CPb3,
                    {
                      [sty.text__displayinvoice___2CPb3OkUjk]: hasVariant(
                        variants,
                        "displayinvoice",
                        "displayinvoice"
                      )
                    }
                  )}
                >
                  {"Quantity"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___1YsOf,
                    {
                      [sty.text__displayinvoice___1YsOfokUjk]: hasVariant(
                        variants,
                        "displayinvoice",
                        "displayinvoice"
                      )
                    }
                  )}
                >
                  {":"}
                </div>

                <div
                  data-plasmic-name={"sap"}
                  data-plasmic-override={overrides.sap}
                  className={classNames(projectcss.all, sty.sap, {
                    [sty.sap__displayinvoice]: hasVariant(
                      variants,
                      "displayinvoice",
                      "displayinvoice"
                    )
                  })}
                >
                  {p.renderPlasmicSlot({
                    defaultContents: "N/A",
                    value: args.qty,
                    className: classNames(sty.slotTargetQty, {
                      [sty.slotTargetQty__displayinvoice]: hasVariant(
                        variants,
                        "displayinvoice",
                        "displayinvoice"
                      )
                    })
                  })}
                </div>
              </div>

              <div
                className={classNames(projectcss.all, sty.freeBox__nSM7, {
                  [sty.freeBox__displayinvoice__nSM7OkUjk]: hasVariant(
                    variants,
                    "displayinvoice",
                    "displayinvoice"
                  )
                })}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__gqKPg,
                    {
                      [sty.text__displayinvoice__gqKPgokUjk]: hasVariant(
                        variants,
                        "displayinvoice",
                        "displayinvoice"
                      )
                    }
                  )}
                >
                  {"Gross Weight"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__lq5XY,
                    {
                      [sty.text__displayinvoice__lq5XYokUjk]: hasVariant(
                        variants,
                        "displayinvoice",
                        "displayinvoice"
                      )
                    }
                  )}
                >
                  {":"}
                </div>

                <div
                  data-plasmic-name={"grn"}
                  data-plasmic-override={overrides.grn}
                  className={classNames(projectcss.all, sty.grn, {
                    [sty.grn__displayinvoice]: hasVariant(
                      variants,
                      "displayinvoice",
                      "displayinvoice"
                    )
                  })}
                >
                  {p.renderPlasmicSlot({
                    defaultContents: "N/A",
                    value: args.gross,
                    className: classNames(sty.slotTargetGross, {
                      [sty.slotTargetGross__displayinvoice]: hasVariant(
                        variants,
                        "displayinvoice",
                        "displayinvoice"
                      )
                    })
                  })}
                </div>
              </div>

              <div
                className={classNames(projectcss.all, sty.freeBox__umBQy, {
                  [sty.freeBox__displayinvoice__umBQyokUjk]: hasVariant(
                    variants,
                    "displayinvoice",
                    "displayinvoice"
                  )
                })}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__gQoas,
                    {
                      [sty.text__displayinvoice__gQoasokUjk]: hasVariant(
                        variants,
                        "displayinvoice",
                        "displayinvoice"
                      )
                    }
                  )}
                >
                  {"Volume Weight"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___7BV7S,
                    {
                      [sty.text__displayinvoice___7BV7SokUjk]: hasVariant(
                        variants,
                        "displayinvoice",
                        "displayinvoice"
                      )
                    }
                  )}
                >
                  {":"}
                </div>

                <div
                  data-plasmic-name={"creditnotevalue"}
                  data-plasmic-override={overrides.creditnotevalue}
                  className={classNames(projectcss.all, sty.creditnotevalue, {
                    [sty.creditnotevalue__displayinvoice]: hasVariant(
                      variants,
                      "displayinvoice",
                      "displayinvoice"
                    )
                  })}
                >
                  {p.renderPlasmicSlot({
                    defaultContents: "N/A",
                    value: args.volume,
                    className: classNames(sty.slotTargetVolume, {
                      [sty.slotTargetVolume__displayinvoice]: hasVariant(
                        variants,
                        "displayinvoice",
                        "displayinvoice"
                      )
                    })
                  })}
                </div>
              </div>

              <div
                className={classNames(projectcss.all, sty.freeBox__gxTFq, {
                  [sty.freeBox__displayinvoice__gxTFqokUjk]: hasVariant(
                    variants,
                    "displayinvoice",
                    "displayinvoice"
                  )
                })}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__kr8ML,
                    {
                      [sty.text__displayinvoice__kr8MLokUjk]: hasVariant(
                        variants,
                        "displayinvoice",
                        "displayinvoice"
                      )
                    }
                  )}
                >
                  {"ETA"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__tNOjk,
                    {
                      [sty.text__displayinvoice__tNOjkokUjk]: hasVariant(
                        variants,
                        "displayinvoice",
                        "displayinvoice"
                      )
                    }
                  )}
                >
                  {":"}
                </div>

                <div
                  data-plasmic-name={"creditnotevalue2"}
                  data-plasmic-override={overrides.creditnotevalue2}
                  className={classNames(projectcss.all, sty.creditnotevalue2, {
                    [sty.creditnotevalue2__displayinvoice]: hasVariant(
                      variants,
                      "displayinvoice",
                      "displayinvoice"
                    )
                  })}
                >
                  {p.renderPlasmicSlot({
                    defaultContents: "N/A",
                    value: args.eta,
                    className: classNames(sty.slotTargetEta, {
                      [sty.slotTargetEta__displayinvoice]: hasVariant(
                        variants,
                        "displayinvoice",
                        "displayinvoice"
                      )
                    })
                  })}
                </div>
              </div>
            </div>
          ) : null}
          {(
            hasVariant(variants, "displayinvoice", "displayinvoice")
              ? true
              : true
          ) ? (
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__uu6Sa, {
                [sty.freeBox__displayinvoice__uu6SaokUjk]: hasVariant(
                  variants,
                  "displayinvoice",
                  "displayinvoice"
                )
              })}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__hgmZr,
                  {
                    [sty.text__displayinvoice__hgmZrokUjk]: hasVariant(
                      variants,
                      "displayinvoice",
                      "displayinvoice"
                    )
                  }
                )}
              >
                {"Order To: "}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__kicXe,
                  {
                    [sty.text__displayinvoice__kicXeokUjk]: hasVariant(
                      variants,
                      "displayinvoice",
                      "displayinvoice"
                    )
                  }
                )}
              >
                {"Ship To:"}
              </div>
            </p.Stack>
          ) : null}
          {(
            hasVariant(variants, "displayinvoice", "displayinvoice")
              ? true
              : true
          ) ? (
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__kbBix, {
                [sty.freeBox__displayinvoice__kbBiXokUjk]: hasVariant(
                  variants,
                  "displayinvoice",
                  "displayinvoice"
                )
              })}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__mUlzL,
                  {
                    [sty.text__displayinvoice__mUlzLokUjk]: hasVariant(
                      variants,
                      "displayinvoice",
                      "displayinvoice"
                    )
                  }
                )}
              >
                {"ABC Company, \nLocation"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__yRQl4,
                  {
                    [sty.text__displayinvoice__yRQl4OkUjk]: hasVariant(
                      variants,
                      "displayinvoice",
                      "displayinvoice"
                    )
                  }
                )}
              >
                {"ABC Company, \nLocation"}
              </div>
            </p.Stack>
          ) : null}
          {(
            hasVariant(variants, "displayinvoice", "displayinvoice")
              ? true
              : true
          ) ? (
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___83W0, {
                [sty.freeBox__displayinvoice___83W0OkUjk]: hasVariant(
                  variants,
                  "displayinvoice",
                  "displayinvoice"
                )
              })}
            >
              <div
                className={classNames(projectcss.all, sty.freeBox__xdGuc, {
                  [sty.freeBox__displayinvoice__xdGucokUjk]: hasVariant(
                    variants,
                    "displayinvoice",
                    "displayinvoice"
                  )
                })}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__cvHgx
                  )}
                >
                  {"Contact:"}
                </div>

                {true ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__wQqkD, {
                      [sty.freeBox__displayinvoice__wQqkDokUjk]: hasVariant(
                        variants,
                        "displayinvoice",
                        "displayinvoice"
                      )
                    })}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___98CQl,
                        {
                          [sty.text__displayinvoice___98CQLokUjk]: hasVariant(
                            variants,
                            "displayinvoice",
                            "displayinvoice"
                          )
                        }
                      )}
                    >
                      {"Name:"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__f7FzI,
                        {
                          [sty.text__displayinvoice__f7FzIokUjk]: hasVariant(
                            variants,
                            "displayinvoice",
                            "displayinvoice"
                          )
                        }
                      )}
                    >
                      {"1234567890"}
                    </div>
                  </p.Stack>
                ) : null}
              </div>

              <div
                className={classNames(projectcss.all, sty.freeBox__xPigo, {
                  [sty.freeBox__displayinvoice__xPigookUjk]: hasVariant(
                    variants,
                    "displayinvoice",
                    "displayinvoice"
                  )
                })}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__uevCp,
                    {
                      [sty.text__displayinvoice__uevCpokUjk]: hasVariant(
                        variants,
                        "displayinvoice",
                        "displayinvoice"
                      )
                    }
                  )}
                >
                  {"Date:"}
                </div>

                {true ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__zMqwK, {
                      [sty.freeBox__displayinvoice__zMqwKokUjk]: hasVariant(
                        variants,
                        "displayinvoice",
                        "displayinvoice"
                      )
                    })}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__nEtQ6,
                        {
                          [sty.text__displayinvoice__nEtQ6OkUjk]: hasVariant(
                            variants,
                            "displayinvoice",
                            "displayinvoice"
                          )
                        }
                      )}
                    >
                      {"1234567890"}
                    </div>
                  </p.Stack>
                ) : null}
              </div>
            </p.Stack>
          ) : null}
          {(
            hasVariant(variants, "displayinvoice", "displayinvoice")
              ? true
              : true
          ) ? (
            <div
              className={classNames(projectcss.all, sty.freeBox__w90E0, {
                [sty.freeBox__displayinvoice__w90E0OkUjk]: hasVariant(
                  variants,
                  "displayinvoice",
                  "displayinvoice"
                )
              })}
            >
              <div
                className={classNames(projectcss.all, sty.freeBox__gGnd, {
                  [sty.freeBox__displayinvoice__gGndokUjk]: hasVariant(
                    variants,
                    "displayinvoice",
                    "displayinvoice"
                  )
                })}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__bfb4M,
                    {
                      [sty.text__displayinvoice__bfb4MokUjk]: hasVariant(
                        variants,
                        "displayinvoice",
                        "displayinvoice"
                      )
                    }
                  )}
                >
                  {"#"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__av2W6,
                    {
                      [sty.text__displayinvoice__av2W6OkUjk]: hasVariant(
                        variants,
                        "displayinvoice",
                        "displayinvoice"
                      )
                    }
                  )}
                >
                  {"Product ID"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__plpYr,
                    {
                      [sty.text__displayinvoice__plpYrokUjk]: hasVariant(
                        variants,
                        "displayinvoice",
                        "displayinvoice"
                      )
                    }
                  )}
                >
                  {"Product"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___2DYr,
                    {
                      [sty.text__displayinvoice___2DYRokUjk]: hasVariant(
                        variants,
                        "displayinvoice",
                        "displayinvoice"
                      )
                    }
                  )}
                >
                  {"Quantity"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__fX3T,
                    {
                      [sty.text__displayinvoice__fX3TokUjk]: hasVariant(
                        variants,
                        "displayinvoice",
                        "displayinvoice"
                      )
                    }
                  )}
                >
                  {"Unit Price"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__n34BD,
                    {
                      [sty.text__displayinvoice__n34BDokUjk]: hasVariant(
                        variants,
                        "displayinvoice",
                        "displayinvoice"
                      )
                    }
                  )}
                >
                  {"Total"}
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.freeBox__alvO)}>
                <div
                  className={classNames(projectcss.all, sty.freeBox__tOAf3, {
                    [sty.freeBox__displayinvoice__tOAf3OkUjk]: hasVariant(
                      variants,
                      "displayinvoice",
                      "displayinvoice"
                    )
                  })}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___3ExPj,
                      {
                        [sty.text__displayinvoice___3ExPjokUjk]: hasVariant(
                          variants,
                          "displayinvoice",
                          "displayinvoice"
                        )
                      }
                    )}
                  >
                    {"#"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__p2Scr,
                      {
                        [sty.text__displayinvoice__p2ScRokUjk]: hasVariant(
                          variants,
                          "displayinvoice",
                          "displayinvoice"
                        )
                      }
                    )}
                  >
                    {"Product ID"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fc19X,
                      {
                        [sty.text__displayinvoice__fc19XokUjk]: hasVariant(
                          variants,
                          "displayinvoice",
                          "displayinvoice"
                        )
                      }
                    )}
                  >
                    {"Product"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___8Vbth,
                      {
                        [sty.text__displayinvoice___8VbtHokUjk]: hasVariant(
                          variants,
                          "displayinvoice",
                          "displayinvoice"
                        )
                      }
                    )}
                  >
                    {"Quantity"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__u4F8O,
                      {
                        [sty.text__displayinvoice__u4F8OokUjk]: hasVariant(
                          variants,
                          "displayinvoice",
                          "displayinvoice"
                        )
                      }
                    )}
                  >
                    {"Unit Price"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mc1PZ,
                      {
                        [sty.text__displayinvoice__mc1PZokUjk]: hasVariant(
                          variants,
                          "displayinvoice",
                          "displayinvoice"
                        )
                      }
                    )}
                  >
                    {"Total"}
                  </div>
                </div>

                {(
                  hasVariant(variants, "displayinvoice", "displayinvoice")
                    ? true
                    : true
                ) ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__oSwR, {
                      [sty.freeBox__displayinvoice__oSwRokUjk]: hasVariant(
                        variants,
                        "displayinvoice",
                        "displayinvoice"
                      )
                    })}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__je19H,
                        {
                          [sty.text__displayinvoice__je19HokUjk]: hasVariant(
                            variants,
                            "displayinvoice",
                            "displayinvoice"
                          )
                        }
                      )}
                    >
                      {"#"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__dXxEh,
                        {
                          [sty.text__displayinvoice__dXxEhokUjk]: hasVariant(
                            variants,
                            "displayinvoice",
                            "displayinvoice"
                          )
                        }
                      )}
                    >
                      {"Product ID"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__fm2Ad,
                        {
                          [sty.text__displayinvoice__fm2ADokUjk]: hasVariant(
                            variants,
                            "displayinvoice",
                            "displayinvoice"
                          )
                        }
                      )}
                    >
                      {"Product"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__omKiI
                      )}
                    >
                      {"Quantity"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___6Hbwa
                      )}
                    >
                      {"Unit Price"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___2Jwrx
                      )}
                    >
                      {"Total"}
                    </div>
                  </div>
                ) : null}
                {(
                  hasVariant(variants, "displayinvoice", "displayinvoice")
                    ? true
                    : true
                ) ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__nsDbH, {
                      [sty.freeBox__displayinvoice__nsDbHokUjk]: hasVariant(
                        variants,
                        "displayinvoice",
                        "displayinvoice"
                      )
                    })}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__hjT1
                      )}
                    >
                      {"#"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__dmpM
                      )}
                    >
                      {"Product ID"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__l9UcQ
                      )}
                    >
                      {"Product"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__t5Kse
                      )}
                    >
                      {"Quantity"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__kWi4
                      )}
                    >
                      {"Unit Price"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__e3Qy9
                      )}
                    >
                      {"Total"}
                    </div>
                  </div>
                ) : null}
                {(
                  hasVariant(variants, "displayinvoice", "displayinvoice")
                    ? true
                    : true
                ) ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__bOoEw, {
                      [sty.freeBox__displayinvoice__bOoEWokUjk]: hasVariant(
                        variants,
                        "displayinvoice",
                        "displayinvoice"
                      )
                    })}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ov5Ir
                      )}
                    >
                      {"#"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__x9WA
                      )}
                    >
                      {"Product ID"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__vrdnz
                      )}
                    >
                      {"Product"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__hesmi
                      )}
                    >
                      {"Quantity"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___6EleG
                      )}
                    >
                      {"Unit Price"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__uR8R
                      )}
                    >
                      {"Total"}
                    </div>
                  </div>
                ) : null}
              </div>
            </div>
          ) : null}
          {(
            hasVariant(variants, "displayinvoice", "displayinvoice")
              ? true
              : true
          ) ? (
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__tyqJz, {
                [sty.freeBox__displayinvoice__tyqJZokUjk]: hasVariant(
                  variants,
                  "displayinvoice",
                  "displayinvoice"
                )
              })}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__eUOhK, {
                  [sty.freeBox__displayinvoice__eUOhKokUjk]: hasVariant(
                    variants,
                    "displayinvoice",
                    "displayinvoice"
                  )
                })}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__pPh3S,
                    {
                      [sty.text__displayinvoice__pPh3SokUjk]: hasVariant(
                        variants,
                        "displayinvoice",
                        "displayinvoice"
                      )
                    }
                  )}
                >
                  {"Sub Total"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___9CNy2,
                    {
                      [sty.text__displayinvoice___9CNy2OkUjk]: hasVariant(
                        variants,
                        "displayinvoice",
                        "displayinvoice"
                      )
                    }
                  )}
                >
                  {"Total"}
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__x0Gh, {
                  [sty.freeBox__displayinvoice__x0GhokUjk]: hasVariant(
                    variants,
                    "displayinvoice",
                    "displayinvoice"
                  )
                })}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__tgDut
                  )}
                >
                  {"Tax"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__d8OL,
                    {
                      [sty.text__displayinvoice__d8OLokUjk]: hasVariant(
                        variants,
                        "displayinvoice",
                        "displayinvoice"
                      )
                    }
                  )}
                >
                  {"Total"}
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__aqxke, {
                  [sty.freeBox__displayinvoice__aqxkEokUjk]: hasVariant(
                    variants,
                    "displayinvoice",
                    "displayinvoice"
                  )
                })}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__auWxq,
                    {
                      [sty.text__displayinvoice__auWxqokUjk]: hasVariant(
                        variants,
                        "displayinvoice",
                        "displayinvoice"
                      )
                    }
                  )}
                >
                  {"Total"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ourag,
                    {
                      [sty.text__displayinvoice__ouraGokUjk]: hasVariant(
                        variants,
                        "displayinvoice",
                        "displayinvoice"
                      )
                    }
                  )}
                >
                  {"Total"}
                </div>
              </p.Stack>
            </p.Stack>
          ) : null}
          {true ? (
            <ButtonB
              data-plasmic-name={"formbutton"}
              data-plasmic-override={overrides.formbutton}
              className={classNames("__wab_instance", sty.formbutton, {
                [sty.formbutton__displayinvoice]: hasVariant(
                  variants,
                  "displayinvoice",
                  "displayinvoice"
                )
              })}
              connectmm={true}
            />
          ) : null}
        </p.Stack>
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "applicationForm",
    "supplier",
    "shipmentmode",
    "origincountry",
    "sap",
    "grn",
    "creditnotevalue",
    "creditnotevalue2",
    "formbutton"
  ],

  applicationForm: [
    "applicationForm",
    "supplier",
    "shipmentmode",
    "origincountry",
    "sap",
    "grn",
    "creditnotevalue",
    "creditnotevalue2",
    "formbutton"
  ],

  supplier: ["supplier"],
  shipmentmode: ["shipmentmode"],
  origincountry: ["origincountry"],
  sap: ["sap"],
  grn: ["grn"],
  creditnotevalue: ["creditnotevalue"],
  creditnotevalue2: ["creditnotevalue2"],
  formbutton: ["formbutton"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicInvoicegeneration__ArgProps,
      internalVariantPropNames: PlasmicInvoicegeneration__VariantProps
    });

    return PlasmicInvoicegeneration__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicInvoicegeneration";
  } else {
    func.displayName = `PlasmicInvoicegeneration.${nodeName}`;
  }
  return func;
}

export const PlasmicInvoicegeneration = Object.assign(
  // Top-level PlasmicInvoicegeneration renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    applicationForm: makeNodeComponent("applicationForm"),
    supplier: makeNodeComponent("supplier"),
    shipmentmode: makeNodeComponent("shipmentmode"),
    origincountry: makeNodeComponent("origincountry"),
    sap: makeNodeComponent("sap"),
    grn: makeNodeComponent("grn"),
    creditnotevalue: makeNodeComponent("creditnotevalue"),
    creditnotevalue2: makeNodeComponent("creditnotevalue2"),
    formbutton: makeNodeComponent("formbutton"),
    // Metadata about props expected for PlasmicInvoicegeneration
    internalVariantProps: PlasmicInvoicegeneration__VariantProps,
    internalArgProps: PlasmicInvoicegeneration__ArgProps
  }
);

export default PlasmicInvoicegeneration;
/* prettier-ignore-end */
