// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5GT6nVB5WgvLWb2iBXTk1E
// Component: -PLz2ilC-Zc
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import ButtonB from "../../ButtonB"; // plasmic-import: oSXCQ8ez26/component
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_project_5162.module.css"; // plasmic-import: 5GT6nVB5WgvLWb2iBXTk1E/projectcss
import sty from "./PlasmicSalesordergeneration.module.css"; // plasmic-import: -PLz2ilC-Zc/css

export const PlasmicSalesordergeneration__VariantProps = new Array(
  "displaysalesorder"
);

export const PlasmicSalesordergeneration__ArgProps = new Array(
  "children",
  "slot",
  "slot2",
  "slot3",
  "slot4",
  "slot5",
  "pono"
);

function PlasmicSalesordergeneration__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(projectcss.all, projectcss.root_reset, sty.root)}
    >
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__zLbSn
        )}
      >
        {"SALES ORDER GENERATION"}
      </div>

      <div
        data-plasmic-name={"applicationForm"}
        data-plasmic-override={overrides.applicationForm}
        className={classNames(projectcss.all, sty.applicationForm, {
          [sty.applicationForm__displaysalesorder]: hasVariant(
            variants,
            "displaysalesorder",
            "displaysalesorder"
          )
        })}
      >
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__w7M6X, {
            [sty.freeBox__displaysalesorder__w7M6XtEf4M]: hasVariant(
              variants,
              "displaysalesorder",
              "displaysalesorder"
            )
          })}
        >
          <div
            className={classNames(projectcss.all, sty.freeBox__yY8Gk, {
              [sty.freeBox__displaysalesorder__yY8GktEf4M]: hasVariant(
                variants,
                "displaysalesorder",
                "displaysalesorder"
              )
            })}
          >
            <div
              className={classNames(projectcss.all, sty.freeBox__bHvUz, {
                [sty.freeBox__displaysalesorder__bHvUztEf4M]: hasVariant(
                  variants,
                  "displaysalesorder",
                  "displaysalesorder"
                )
              })}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__vOjIe,
                  {
                    [sty.text__displaysalesorder__vOjIetEf4M]: hasVariant(
                      variants,
                      "displaysalesorder",
                      "displaysalesorder"
                    )
                  }
                )}
              >
                {hasVariant(variants, "displaysalesorder", "displaysalesorder")
                  ? "PO No"
                  : "Order ID"}
              </div>

              {true ? (
                <div
                  className={classNames(projectcss.all, sty.freeBox__pfmEn, {
                    [sty.freeBox__displaysalesorder__pfmEntEf4M]: hasVariant(
                      variants,
                      "displaysalesorder",
                      "displaysalesorder"
                    )
                  })}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fjkCq
                    )}
                  >
                    {"#"}
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__oqnY, {
                      [sty.freeBox__displaysalesorder__oqnYtEf4M]: hasVariant(
                        variants,
                        "displaysalesorder",
                        "displaysalesorder"
                      )
                    })}
                  >
                    {p.renderPlasmicSlot({
                      defaultContents: "ABC123",
                      value: args.pono,
                      className: classNames(sty.slotTargetPono, {
                        [sty.slotTargetPono__displaysalesorder]: hasVariant(
                          variants,
                          "displaysalesorder",
                          "displaysalesorder"
                        )
                      })
                    })}
                  </div>
                </div>
              ) : null}
            </div>
          </div>

          {(
            hasVariant(variants, "displaysalesorder", "displaysalesorder")
              ? true
              : false
          ) ? (
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__b4EWt, {
                [sty.freeBox__displaysalesorder__b4EWttEf4M]: hasVariant(
                  variants,
                  "displaysalesorder",
                  "displaysalesorder"
                )
              })}
            >
              {(
                hasVariant(variants, "displaysalesorder", "displaysalesorder")
                  ? true
                  : true
              ) ? (
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__s59Kq,
                    {
                      [sty.text__displaysalesorder__s59KQtEf4M]: hasVariant(
                        variants,
                        "displaysalesorder",
                        "displaysalesorder"
                      )
                    }
                  )}
                >
                  {"Order To: "}
                </div>
              ) : null}
              {(
                hasVariant(variants, "displaysalesorder", "displaysalesorder")
                  ? true
                  : true
              ) ? (
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___1FyxZ,
                    {
                      [sty.text__displaysalesorder___1FyxZtEf4M]: hasVariant(
                        variants,
                        "displaysalesorder",
                        "displaysalesorder"
                      )
                    }
                  )}
                >
                  {"Ship To:"}
                </div>
              ) : null}
            </p.Stack>
          ) : null}
          {(
            hasVariant(variants, "displaysalesorder", "displaysalesorder")
              ? true
              : true
          ) ? (
            <div
              className={classNames(projectcss.all, sty.freeBox__vBrpa, {
                [sty.freeBox__displaysalesorder__vBrpatEf4M]: hasVariant(
                  variants,
                  "displaysalesorder",
                  "displaysalesorder"
                )
              })}
            >
              <div
                className={classNames(projectcss.all, sty.freeBox__mjsTp, {
                  [sty.freeBox__displaysalesorder__mjsTPtEf4M]: hasVariant(
                    variants,
                    "displaysalesorder",
                    "displaysalesorder"
                  )
                })}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ktQqf,
                    {
                      [sty.text__displaysalesorder__ktQqftEf4M]: hasVariant(
                        variants,
                        "displaysalesorder",
                        "displaysalesorder"
                      )
                    }
                  )}
                >
                  {"Supplier Name"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__mSwmf,
                    {
                      [sty.text__displaysalesorder__mSwmftEf4M]: hasVariant(
                        variants,
                        "displaysalesorder",
                        "displaysalesorder"
                      )
                    }
                  )}
                >
                  {":"}
                </div>

                <div
                  data-plasmic-name={"supplier"}
                  data-plasmic-override={overrides.supplier}
                  className={classNames(projectcss.all, sty.supplier, {
                    [sty.supplier__displaysalesorder]: hasVariant(
                      variants,
                      "displaysalesorder",
                      "displaysalesorder"
                    )
                  })}
                >
                  {p.renderPlasmicSlot({
                    defaultContents: "N/A",
                    value: args.children,
                    className: classNames(sty.slotTargetChildren, {
                      [sty.slotTargetChildren__displaysalesorder]: hasVariant(
                        variants,
                        "displaysalesorder",
                        "displaysalesorder"
                      )
                    })
                  })}
                </div>
              </div>

              <div
                className={classNames(projectcss.all, sty.freeBox__x4R0, {
                  [sty.freeBox__displaysalesorder__x4R0TEf4M]: hasVariant(
                    variants,
                    "displaysalesorder",
                    "displaysalesorder"
                  )
                })}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__anpj4,
                    {
                      [sty.text__displaysalesorder__anpj4TEf4M]: hasVariant(
                        variants,
                        "displaysalesorder",
                        "displaysalesorder"
                      )
                    }
                  )}
                >
                  {"Mode of Shipment"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___15DvJ,
                    {
                      [sty.text__displaysalesorder___15DvJtEf4M]: hasVariant(
                        variants,
                        "displaysalesorder",
                        "displaysalesorder"
                      )
                    }
                  )}
                >
                  {":"}
                </div>

                <div
                  data-plasmic-name={"shipmentmode"}
                  data-plasmic-override={overrides.shipmentmode}
                  className={classNames(projectcss.all, sty.shipmentmode, {
                    [sty.shipmentmode__displaysalesorder]: hasVariant(
                      variants,
                      "displaysalesorder",
                      "displaysalesorder"
                    )
                  })}
                >
                  {p.renderPlasmicSlot({
                    defaultContents: "N/A",
                    value: args.slot,
                    className: classNames(sty.slotTargetSlot, {
                      [sty.slotTargetSlot__displaysalesorder]: hasVariant(
                        variants,
                        "displaysalesorder",
                        "displaysalesorder"
                      )
                    })
                  })}
                </div>
              </div>

              <div
                className={classNames(projectcss.all, sty.freeBox__nbokJ, {
                  [sty.freeBox__displaysalesorder__nbokJtEf4M]: hasVariant(
                    variants,
                    "displaysalesorder",
                    "displaysalesorder"
                  )
                })}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___5TUc,
                    {
                      [sty.text__displaysalesorder___5TUctEf4M]: hasVariant(
                        variants,
                        "displaysalesorder",
                        "displaysalesorder"
                      )
                    }
                  )}
                >
                  {"Country of Origin"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__mWFfr,
                    {
                      [sty.text__displaysalesorder__mWFfrtEf4M]: hasVariant(
                        variants,
                        "displaysalesorder",
                        "displaysalesorder"
                      )
                    }
                  )}
                >
                  {":"}
                </div>

                <div
                  data-plasmic-name={"origincountry"}
                  data-plasmic-override={overrides.origincountry}
                  className={classNames(projectcss.all, sty.origincountry, {
                    [sty.origincountry__displaysalesorder]: hasVariant(
                      variants,
                      "displaysalesorder",
                      "displaysalesorder"
                    )
                  })}
                >
                  {p.renderPlasmicSlot({
                    defaultContents: "N/A",
                    value: args.slot2,
                    className: classNames(sty.slotTargetSlot2, {
                      [sty.slotTargetSlot2__displaysalesorder]: hasVariant(
                        variants,
                        "displaysalesorder",
                        "displaysalesorder"
                      )
                    })
                  })}
                </div>
              </div>

              <div
                className={classNames(projectcss.all, sty.freeBox__auUkj, {
                  [sty.freeBox__displaysalesorder__auUkJtEf4M]: hasVariant(
                    variants,
                    "displaysalesorder",
                    "displaysalesorder"
                  )
                })}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__zbaIm,
                    {
                      [sty.text__displaysalesorder__zbaImtEf4M]: hasVariant(
                        variants,
                        "displaysalesorder",
                        "displaysalesorder"
                      )
                    }
                  )}
                >
                  {"SAP Status"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__xsU9M,
                    {
                      [sty.text__displaysalesorder__xsU9MtEf4M]: hasVariant(
                        variants,
                        "displaysalesorder",
                        "displaysalesorder"
                      )
                    }
                  )}
                >
                  {":"}
                </div>

                <div
                  data-plasmic-name={"sap"}
                  data-plasmic-override={overrides.sap}
                  className={classNames(projectcss.all, sty.sap, {
                    [sty.sap__displaysalesorder]: hasVariant(
                      variants,
                      "displaysalesorder",
                      "displaysalesorder"
                    )
                  })}
                >
                  {p.renderPlasmicSlot({
                    defaultContents: "N/A",
                    value: args.slot3,
                    className: classNames(sty.slotTargetSlot3, {
                      [sty.slotTargetSlot3__displaysalesorder]: hasVariant(
                        variants,
                        "displaysalesorder",
                        "displaysalesorder"
                      )
                    })
                  })}
                </div>
              </div>

              <div
                className={classNames(projectcss.all, sty.freeBox__xuFu9, {
                  [sty.freeBox__displaysalesorder__xuFu9TEf4M]: hasVariant(
                    variants,
                    "displaysalesorder",
                    "displaysalesorder"
                  )
                })}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__mFrrL,
                    {
                      [sty.text__displaysalesorder__mFrrLtEf4M]: hasVariant(
                        variants,
                        "displaysalesorder",
                        "displaysalesorder"
                      )
                    }
                  )}
                >
                  {"GRN Number"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__xebXu,
                    {
                      [sty.text__displaysalesorder__xebXutEf4M]: hasVariant(
                        variants,
                        "displaysalesorder",
                        "displaysalesorder"
                      )
                    }
                  )}
                >
                  {":"}
                </div>

                <div
                  data-plasmic-name={"grn"}
                  data-plasmic-override={overrides.grn}
                  className={classNames(projectcss.all, sty.grn, {
                    [sty.grn__displaysalesorder]: hasVariant(
                      variants,
                      "displaysalesorder",
                      "displaysalesorder"
                    )
                  })}
                >
                  {p.renderPlasmicSlot({
                    defaultContents: "N/A",
                    value: args.slot4,
                    className: classNames(sty.slotTargetSlot4, {
                      [sty.slotTargetSlot4__displaysalesorder]: hasVariant(
                        variants,
                        "displaysalesorder",
                        "displaysalesorder"
                      )
                    })
                  })}
                </div>
              </div>

              <div
                className={classNames(projectcss.all, sty.freeBox__yTdH5, {
                  [sty.freeBox__displaysalesorder__yTdH5TEf4M]: hasVariant(
                    variants,
                    "displaysalesorder",
                    "displaysalesorder"
                  )
                })}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___8U67Z,
                    {
                      [sty.text__displaysalesorder___8U67ZtEf4M]: hasVariant(
                        variants,
                        "displaysalesorder",
                        "displaysalesorder"
                      )
                    }
                  )}
                >
                  {"Credit Note Value"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__yaMpg,
                    {
                      [sty.text__displaysalesorder__yaMpGtEf4M]: hasVariant(
                        variants,
                        "displaysalesorder",
                        "displaysalesorder"
                      )
                    }
                  )}
                >
                  {":"}
                </div>

                <div
                  data-plasmic-name={"creditnotevalue"}
                  data-plasmic-override={overrides.creditnotevalue}
                  className={classNames(projectcss.all, sty.creditnotevalue, {
                    [sty.creditnotevalue__displaysalesorder]: hasVariant(
                      variants,
                      "displaysalesorder",
                      "displaysalesorder"
                    )
                  })}
                >
                  {p.renderPlasmicSlot({
                    defaultContents: "N/A",
                    value: args.slot5,
                    className: classNames(sty.slotTargetSlot5, {
                      [sty.slotTargetSlot5__displaysalesorder]: hasVariant(
                        variants,
                        "displaysalesorder",
                        "displaysalesorder"
                      )
                    })
                  })}
                </div>
              </div>

              <div
                className={classNames(projectcss.all, sty.freeBox___2FeWl, {
                  [sty.freeBox__displaysalesorder___2FeWLtEf4M]: hasVariant(
                    variants,
                    "displaysalesorder",
                    "displaysalesorder"
                  )
                })}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ddB3I,
                    {
                      [sty.text__displaysalesorder__ddB3ItEf4M]: hasVariant(
                        variants,
                        "displaysalesorder",
                        "displaysalesorder"
                      )
                    }
                  )}
                >
                  {"Balance Payable (Total Invoice Value - Credit Note Amount"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__qPy9J,
                    {
                      [sty.text__displaysalesorder__qPy9JtEf4M]: hasVariant(
                        variants,
                        "displaysalesorder",
                        "displaysalesorder"
                      )
                    }
                  )}
                >
                  {":"}
                </div>

                <div
                  data-plasmic-name={"balance2"}
                  data-plasmic-override={overrides.balance2}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.balance2,
                    {
                      [sty.balance2__displaysalesorder]: hasVariant(
                        variants,
                        "displaysalesorder",
                        "displaysalesorder"
                      )
                    }
                  )}
                >
                  {"$"}
                </div>

                <div
                  data-plasmic-name={"balance"}
                  data-plasmic-override={overrides.balance}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.balance,
                    {
                      [sty.balance__displaysalesorder]: hasVariant(
                        variants,
                        "displaysalesorder",
                        "displaysalesorder"
                      )
                    }
                  )}
                >
                  {"N/A"}
                </div>
              </div>
            </div>
          ) : null}
          {(
            hasVariant(variants, "displaysalesorder", "displaysalesorder")
              ? true
              : true
          ) ? (
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___245Hm, {
                [sty.freeBox__displaysalesorder___245HmtEf4M]: hasVariant(
                  variants,
                  "displaysalesorder",
                  "displaysalesorder"
                )
              })}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__bWoK0,
                  {
                    [sty.text__displaysalesorder__bWoK0TEf4M]: hasVariant(
                      variants,
                      "displaysalesorder",
                      "displaysalesorder"
                    )
                  }
                )}
              >
                {"Order To: "}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__cjsD,
                  {
                    [sty.text__displaysalesorder__cjsDTEf4M]: hasVariant(
                      variants,
                      "displaysalesorder",
                      "displaysalesorder"
                    )
                  }
                )}
              >
                {"Ship To:"}
              </div>
            </p.Stack>
          ) : null}
          {(
            hasVariant(variants, "displaysalesorder", "displaysalesorder")
              ? true
              : true
          ) ? (
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__vWOoc, {
                [sty.freeBox__displaysalesorder__vWOoctEf4M]: hasVariant(
                  variants,
                  "displaysalesorder",
                  "displaysalesorder"
                )
              })}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___8VMV,
                  {
                    [sty.text__displaysalesorder___8VMVtEf4M]: hasVariant(
                      variants,
                      "displaysalesorder",
                      "displaysalesorder"
                    )
                  }
                )}
              >
                {"ABC Company, \nLocation"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__q5G7Q,
                  {
                    [sty.text__displaysalesorder__q5G7QtEf4M]: hasVariant(
                      variants,
                      "displaysalesorder",
                      "displaysalesorder"
                    )
                  }
                )}
              >
                {"ABC Company, \nLocation"}
              </div>
            </p.Stack>
          ) : null}
          {(
            hasVariant(variants, "displaysalesorder", "displaysalesorder")
              ? true
              : true
          ) ? (
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__cuKyd, {
                [sty.freeBox__displaysalesorder__cuKyDtEf4M]: hasVariant(
                  variants,
                  "displaysalesorder",
                  "displaysalesorder"
                )
              })}
            >
              <div
                className={classNames(projectcss.all, sty.freeBox__eT7O, {
                  [sty.freeBox__displaysalesorder__eT7OtEf4M]: hasVariant(
                    variants,
                    "displaysalesorder",
                    "displaysalesorder"
                  )
                })}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ewHwh
                  )}
                >
                  {"Contact:"}
                </div>

                {true ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__zvzcC, {
                      [sty.freeBox__displaysalesorder__zvzcCtEf4M]: hasVariant(
                        variants,
                        "displaysalesorder",
                        "displaysalesorder"
                      )
                    })}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ceY4R,
                        {
                          [sty.text__displaysalesorder__ceY4RtEf4M]: hasVariant(
                            variants,
                            "displaysalesorder",
                            "displaysalesorder"
                          )
                        }
                      )}
                    >
                      {"Name:"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ea37B,
                        {
                          [sty.text__displaysalesorder__ea37BtEf4M]: hasVariant(
                            variants,
                            "displaysalesorder",
                            "displaysalesorder"
                          )
                        }
                      )}
                    >
                      {"1234567890"}
                    </div>
                  </p.Stack>
                ) : null}
              </div>

              <div
                className={classNames(projectcss.all, sty.freeBox__ld89R, {
                  [sty.freeBox__displaysalesorder__ld89RtEf4M]: hasVariant(
                    variants,
                    "displaysalesorder",
                    "displaysalesorder"
                  )
                })}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__qkv2R,
                    {
                      [sty.text__displaysalesorder__qkv2RtEf4M]: hasVariant(
                        variants,
                        "displaysalesorder",
                        "displaysalesorder"
                      )
                    }
                  )}
                >
                  {"Date:"}
                </div>

                {true ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__znHNl, {
                      [sty.freeBox__displaysalesorder__znHNltEf4M]: hasVariant(
                        variants,
                        "displaysalesorder",
                        "displaysalesorder"
                      )
                    })}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__vpA3B,
                        {
                          [sty.text__displaysalesorder__vpA3BtEf4M]: hasVariant(
                            variants,
                            "displaysalesorder",
                            "displaysalesorder"
                          )
                        }
                      )}
                    >
                      {"1234567890"}
                    </div>
                  </p.Stack>
                ) : null}
              </div>
            </p.Stack>
          ) : null}
          {(
            hasVariant(variants, "displaysalesorder", "displaysalesorder")
              ? true
              : true
          ) ? (
            <div
              className={classNames(projectcss.all, sty.freeBox__s2Ozy, {
                [sty.freeBox__displaysalesorder__s2OzytEf4M]: hasVariant(
                  variants,
                  "displaysalesorder",
                  "displaysalesorder"
                )
              })}
            >
              <div
                className={classNames(projectcss.all, sty.freeBox___0WUzi, {
                  [sty.freeBox__displaysalesorder___0WUzitEf4M]: hasVariant(
                    variants,
                    "displaysalesorder",
                    "displaysalesorder"
                  )
                })}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__bOtOp,
                    {
                      [sty.text__displaysalesorder__bOtOptEf4M]: hasVariant(
                        variants,
                        "displaysalesorder",
                        "displaysalesorder"
                      )
                    }
                  )}
                >
                  {"#"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__bqron,
                    {
                      [sty.text__displaysalesorder__bqrontEf4M]: hasVariant(
                        variants,
                        "displaysalesorder",
                        "displaysalesorder"
                      )
                    }
                  )}
                >
                  {"Product ID"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__dXeVq,
                    {
                      [sty.text__displaysalesorder__dXeVQtEf4M]: hasVariant(
                        variants,
                        "displaysalesorder",
                        "displaysalesorder"
                      )
                    }
                  )}
                >
                  {"Product"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__o8Yg1,
                    {
                      [sty.text__displaysalesorder__o8Yg1TEf4M]: hasVariant(
                        variants,
                        "displaysalesorder",
                        "displaysalesorder"
                      )
                    }
                  )}
                >
                  {"Quantity"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__pnLps,
                    {
                      [sty.text__displaysalesorder__pnLpstEf4M]: hasVariant(
                        variants,
                        "displaysalesorder",
                        "displaysalesorder"
                      )
                    }
                  )}
                >
                  {"Unit Price"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___4A41G,
                    {
                      [sty.text__displaysalesorder___4A41GtEf4M]: hasVariant(
                        variants,
                        "displaysalesorder",
                        "displaysalesorder"
                      )
                    }
                  )}
                >
                  {"Total"}
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.freeBox__dqBug)}>
                <div
                  className={classNames(projectcss.all, sty.freeBox__zmo0S, {
                    [sty.freeBox__displaysalesorder__zmo0StEf4M]: hasVariant(
                      variants,
                      "displaysalesorder",
                      "displaysalesorder"
                    )
                  })}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__uaGfx,
                      {
                        [sty.text__displaysalesorder__uaGfxtEf4M]: hasVariant(
                          variants,
                          "displaysalesorder",
                          "displaysalesorder"
                        )
                      }
                    )}
                  >
                    {"#"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___46A5X,
                      {
                        [sty.text__displaysalesorder___46A5XtEf4M]: hasVariant(
                          variants,
                          "displaysalesorder",
                          "displaysalesorder"
                        )
                      }
                    )}
                  >
                    {"Product ID"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__z033A,
                      {
                        [sty.text__displaysalesorder__z033AtEf4M]: hasVariant(
                          variants,
                          "displaysalesorder",
                          "displaysalesorder"
                        )
                      }
                    )}
                  >
                    {"Product"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__riOv9,
                      {
                        [sty.text__displaysalesorder__riOv9TEf4M]: hasVariant(
                          variants,
                          "displaysalesorder",
                          "displaysalesorder"
                        )
                      }
                    )}
                  >
                    {"Quantity"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__tZVfG,
                      {
                        [sty.text__displaysalesorder__tZVfGtEf4M]: hasVariant(
                          variants,
                          "displaysalesorder",
                          "displaysalesorder"
                        )
                      }
                    )}
                  >
                    {"Unit Price"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gSSc,
                      {
                        [sty.text__displaysalesorder__gSSCtEf4M]: hasVariant(
                          variants,
                          "displaysalesorder",
                          "displaysalesorder"
                        )
                      }
                    )}
                  >
                    {"Total"}
                  </div>
                </div>

                {(
                  hasVariant(variants, "displaysalesorder", "displaysalesorder")
                    ? true
                    : true
                ) ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox___5Wzvb, {
                      [sty.freeBox__displaysalesorder___5WzvbtEf4M]: hasVariant(
                        variants,
                        "displaysalesorder",
                        "displaysalesorder"
                      )
                    })}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___5PwY,
                        {
                          [sty.text__displaysalesorder___5PwYtEf4M]: hasVariant(
                            variants,
                            "displaysalesorder",
                            "displaysalesorder"
                          )
                        }
                      )}
                    >
                      {"#"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__iYYiU,
                        {
                          [sty.text__displaysalesorder__iYYiUtEf4M]: hasVariant(
                            variants,
                            "displaysalesorder",
                            "displaysalesorder"
                          )
                        }
                      )}
                    >
                      {"Product ID"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__i4Wih,
                        {
                          [sty.text__displaysalesorder__i4WiHtEf4M]: hasVariant(
                            variants,
                            "displaysalesorder",
                            "displaysalesorder"
                          )
                        }
                      )}
                    >
                      {"Product"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__h9F3K
                      )}
                    >
                      {"Quantity"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__jrSsH
                      )}
                    >
                      {"Unit Price"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__xDmM2
                      )}
                    >
                      {"Total"}
                    </div>
                  </div>
                ) : null}
                {(
                  hasVariant(variants, "displaysalesorder", "displaysalesorder")
                    ? true
                    : true
                ) ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox___7M5TU, {
                      [sty.freeBox__displaysalesorder___7M5TUtEf4M]: hasVariant(
                        variants,
                        "displaysalesorder",
                        "displaysalesorder"
                      )
                    })}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___73Xwe
                      )}
                    >
                      {"#"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__fJwMv
                      )}
                    >
                      {"Product ID"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__xbR8
                      )}
                    >
                      {"Product"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__kBqKt
                      )}
                    >
                      {"Quantity"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__iCFws
                      )}
                    >
                      {"Unit Price"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__mADzw
                      )}
                    >
                      {"Total"}
                    </div>
                  </div>
                ) : null}
                {(
                  hasVariant(variants, "displaysalesorder", "displaysalesorder")
                    ? true
                    : true
                ) ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__lwuNg, {
                      [sty.freeBox__displaysalesorder__lwuNGtEf4M]: hasVariant(
                        variants,
                        "displaysalesorder",
                        "displaysalesorder"
                      )
                    })}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__lpHUz
                      )}
                    >
                      {"#"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___86PmW
                      )}
                    >
                      {"Product ID"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__idD0D
                      )}
                    >
                      {"Product"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___4OHxq
                      )}
                    >
                      {"Quantity"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__yqufN
                      )}
                    >
                      {"Unit Price"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__gbWq5
                      )}
                    >
                      {"Total"}
                    </div>
                  </div>
                ) : null}
              </div>
            </div>
          ) : null}
          {(
            hasVariant(variants, "displaysalesorder", "displaysalesorder")
              ? true
              : true
          ) ? (
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__aXv47, {
                [sty.freeBox__displaysalesorder__aXv47TEf4M]: hasVariant(
                  variants,
                  "displaysalesorder",
                  "displaysalesorder"
                )
              })}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___9EyPa, {
                  [sty.freeBox__displaysalesorder___9EyPAtEf4M]: hasVariant(
                    variants,
                    "displaysalesorder",
                    "displaysalesorder"
                  )
                })}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__zcGxz,
                    {
                      [sty.text__displaysalesorder__zcGxZtEf4M]: hasVariant(
                        variants,
                        "displaysalesorder",
                        "displaysalesorder"
                      )
                    }
                  )}
                >
                  {"Sub Total"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__k92Ac,
                    {
                      [sty.text__displaysalesorder__k92ActEf4M]: hasVariant(
                        variants,
                        "displaysalesorder",
                        "displaysalesorder"
                      )
                    }
                  )}
                >
                  {"Total"}
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__xILdf, {
                  [sty.freeBox__displaysalesorder__xILdftEf4M]: hasVariant(
                    variants,
                    "displaysalesorder",
                    "displaysalesorder"
                  )
                })}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__oOyxM
                  )}
                >
                  {"Tax"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__kluIb,
                    {
                      [sty.text__displaysalesorder__kluIBtEf4M]: hasVariant(
                        variants,
                        "displaysalesorder",
                        "displaysalesorder"
                      )
                    }
                  )}
                >
                  {"Total"}
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__f3KBs, {
                  [sty.freeBox__displaysalesorder__f3KBStEf4M]: hasVariant(
                    variants,
                    "displaysalesorder",
                    "displaysalesorder"
                  )
                })}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ovPbO,
                    {
                      [sty.text__displaysalesorder__ovPbOtEf4M]: hasVariant(
                        variants,
                        "displaysalesorder",
                        "displaysalesorder"
                      )
                    }
                  )}
                >
                  {"Total"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__m8J1O,
                    {
                      [sty.text__displaysalesorder__m8J1OtEf4M]: hasVariant(
                        variants,
                        "displaysalesorder",
                        "displaysalesorder"
                      )
                    }
                  )}
                >
                  {"Total"}
                </div>
              </p.Stack>
            </p.Stack>
          ) : null}
          {true ? (
            <ButtonB
              data-plasmic-name={"formbutton"}
              data-plasmic-override={overrides.formbutton}
              className={classNames("__wab_instance", sty.formbutton, {
                [sty.formbutton__displaysalesorder]: hasVariant(
                  variants,
                  "displaysalesorder",
                  "displaysalesorder"
                )
              })}
              connectmm={true}
            />
          ) : null}
        </p.Stack>
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "applicationForm",
    "supplier",
    "shipmentmode",
    "origincountry",
    "sap",
    "grn",
    "creditnotevalue",
    "balance2",
    "balance",
    "formbutton"
  ],

  applicationForm: [
    "applicationForm",
    "supplier",
    "shipmentmode",
    "origincountry",
    "sap",
    "grn",
    "creditnotevalue",
    "balance2",
    "balance",
    "formbutton"
  ],

  supplier: ["supplier"],
  shipmentmode: ["shipmentmode"],
  origincountry: ["origincountry"],
  sap: ["sap"],
  grn: ["grn"],
  creditnotevalue: ["creditnotevalue"],
  balance2: ["balance2"],
  balance: ["balance"],
  formbutton: ["formbutton"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicSalesordergeneration__ArgProps,
      internalVariantPropNames: PlasmicSalesordergeneration__VariantProps
    });

    return PlasmicSalesordergeneration__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSalesordergeneration";
  } else {
    func.displayName = `PlasmicSalesordergeneration.${nodeName}`;
  }
  return func;
}

export const PlasmicSalesordergeneration = Object.assign(
  // Top-level PlasmicSalesordergeneration renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    applicationForm: makeNodeComponent("applicationForm"),
    supplier: makeNodeComponent("supplier"),
    shipmentmode: makeNodeComponent("shipmentmode"),
    origincountry: makeNodeComponent("origincountry"),
    sap: makeNodeComponent("sap"),
    grn: makeNodeComponent("grn"),
    creditnotevalue: makeNodeComponent("creditnotevalue"),
    balance2: makeNodeComponent("balance2"),
    balance: makeNodeComponent("balance"),
    formbutton: makeNodeComponent("formbutton"),
    // Metadata about props expected for PlasmicSalesordergeneration
    internalVariantProps: PlasmicSalesordergeneration__VariantProps,
    internalArgProps: PlasmicSalesordergeneration__ArgProps
  }
);

export default PlasmicSalesordergeneration;
/* prettier-ignore-end */
