// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5GT6nVB5WgvLWb2iBXTk1E
// Component: 6aKy4XMcUD
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import Walletstatus from "../../Walletstatus"; // plasmic-import: yl_7FX-no3/component
import TextInput from "../../TextInput"; // plasmic-import: mnEoyzyDnh9/component
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_project_5162.module.css"; // plasmic-import: 5GT6nVB5WgvLWb2iBXTk1E/projectcss
import sty from "./PlasmicVerifyId.module.css"; // plasmic-import: 6aKy4XMcUD/css
import potraitjpgH0YtZTpqU from "./images/potraitjpg.jpeg"; // plasmic-import: h0YtZTpqU/picture

export const PlasmicVerifyId__VariantProps = new Array("displayId", "notfound");

export const PlasmicVerifyId__ArgProps = new Array(
  "nationality",
  "name",
  "docno",
  "dob",
  "issued",
  "expiry",
  "sex"
);

function PlasmicVerifyId__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(projectcss.all, projectcss.root_reset, sty.root)}
    >
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__m0Lqc
        )}
      >
        {"VERIFY ID CARD"}
      </div>

      <div
        data-plasmic-name={"applicationForm"}
        data-plasmic-override={overrides.applicationForm}
        className={classNames(projectcss.all, sty.applicationForm, {
          [sty.applicationForm__displayId]: hasVariant(
            variants,
            "displayId",
            "displayId"
          ),

          [sty.applicationForm__notfound]: hasVariant(
            variants,
            "notfound",
            "notfound"
          )
        })}
      >
        {false ? (
          <div className={classNames(projectcss.all, sty.freeBox__tyPfi)}>
            {true ? (
              <Walletstatus
                data-plasmic-name={"walletmount"}
                data-plasmic-override={overrides.walletmount}
                className={classNames("__wab_instance", sty.walletmount)}
              />
            ) : null}

            <div
              data-plasmic-name={"frame3"}
              data-plasmic-override={overrides.frame3}
              className={classNames(projectcss.all, sty.frame3)}
            >
              <div
                data-plasmic-name={"graphiteLogo2"}
                data-plasmic-override={overrides.graphiteLogo2}
                className={classNames(projectcss.all, sty.graphiteLogo2)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__jySyg
                )}
              >
                {"POWERED BY"}
              </div>
            </div>
          </div>
        ) : null}
        {(hasVariant(variants, "displayId", "displayId") ? true : true) ? (
          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__xkTbv, {
              [sty.freeBox__displayId__xkTbvXa4I6]: hasVariant(
                variants,
                "displayId",
                "displayId"
              )
            })}
          >
            {(hasVariant(variants, "displayId", "displayId") ? false : true) ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___23Pex, {
                  [sty.freeBox__displayId___23Pexxa4I6]: hasVariant(
                    variants,
                    "displayId",
                    "displayId"
                  )
                })}
              >
                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__vYMh)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__rsacx
                      )}
                    >
                      {"Enter Token Verification No."}
                    </div>
                  </div>
                ) : null}

                <TextInput
                  data-plasmic-name={"tokenno"}
                  data-plasmic-override={overrides.tokenno}
                  className={classNames("__wab_instance", sty.tokenno, {
                    [sty.tokenno__notfound]: hasVariant(
                      variants,
                      "notfound",
                      "notfound"
                    )
                  })}
                  placeholder={"Token ID (Ex. JB118UI)"}
                />

                <button
                  data-plasmic-name={"verifyidbutton"}
                  data-plasmic-override={overrides.verifyidbutton}
                  className={classNames(
                    projectcss.button,
                    projectcss.__wab_text,
                    sty.verifyidbutton
                  )}
                >
                  {"Submit"}
                </button>
              </p.Stack>
            ) : null}
          </p.Stack>
        ) : null}
        {(hasVariant(variants, "displayId", "displayId") ? true : true) ? (
          <div
            data-plasmic-name={"idstack"}
            data-plasmic-override={overrides.idstack}
            className={classNames(projectcss.all, sty.idstack, {
              [sty.idstack__displayId]: hasVariant(
                variants,
                "displayId",
                "displayId"
              )
            })}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__o3Gr6,
                {
                  [sty.text__displayId__o3Gr6Xa4I6]: hasVariant(
                    variants,
                    "displayId",
                    "displayId"
                  )
                }
              )}
            >
              {"Establishment ID"}
            </div>

            <div
              className={classNames(projectcss.all, sty.freeBox___4JtSl, {
                [sty.freeBox__displayId___4JtSlXa4I6]: hasVariant(
                  variants,
                  "displayId",
                  "displayId"
                )
              })}
            >
              <p.PlasmicImg
                data-plasmic-name={"img"}
                data-plasmic-override={overrides.img}
                alt={""}
                className={classNames(sty.img, {
                  [sty.img__displayId]: hasVariant(
                    variants,
                    "displayId",
                    "displayId"
                  )
                })}
                displayHeight={"150px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"64%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"150px"}
                loading={"lazy"}
                src={{
                  src: potraitjpgH0YtZTpqU,
                  fullWidth: 1920,
                  fullHeight: 1080,
                  aspectRatio: undefined
                }}
              />

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__gMzA, {
                  [sty.freeBox__displayId__gMzAxa4I6]: hasVariant(
                    variants,
                    "displayId",
                    "displayId"
                  )
                })}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___3NyQl,
                    {
                      [sty.text__displayId___3NyQlxa4I6]: hasVariant(
                        variants,
                        "displayId",
                        "displayId"
                      )
                    }
                  )}
                >
                  {"Applicant Details"}
                </div>

                <div
                  className={classNames(projectcss.all, sty.freeBox__bvHml, {
                    [sty.freeBox__displayId__bvHmlxa4I6]: hasVariant(
                      variants,
                      "displayId",
                      "displayId"
                    )
                  })}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__h8CVh, {
                      [sty.freeBox__displayId__h8CVhXa4I6]: hasVariant(
                        variants,
                        "displayId",
                        "displayId"
                      )
                    })}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ww3Lc,
                        {
                          [sty.text__displayId__ww3LcXa4I6]: hasVariant(
                            variants,
                            "displayId",
                            "displayId"
                          )
                        }
                      )}
                    >
                      {"Nationality"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___2A37F,
                        {
                          [sty.text__displayId___2A37FXa4I6]: hasVariant(
                            variants,
                            "displayId",
                            "displayId"
                          )
                        }
                      )}
                    >
                      {":"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox__j2Y06,
                        {
                          [sty.freeBox__displayId__j2Y06Xa4I6]: hasVariant(
                            variants,
                            "displayId",
                            "displayId"
                          )
                        }
                      )}
                    >
                      {p.renderPlasmicSlot({
                        defaultContents: "N/A",
                        value: args.nationality,
                        className: classNames(sty.slotTargetNationality, {
                          [sty.slotTargetNationality__displayId]: hasVariant(
                            variants,
                            "displayId",
                            "displayId"
                          )
                        })
                      })}
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__iYx6L, {
                      [sty.freeBox__displayId__iYx6Lxa4I6]: hasVariant(
                        variants,
                        "displayId",
                        "displayId"
                      )
                    })}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__yw2Rp,
                        {
                          [sty.text__displayId__yw2RpXa4I6]: hasVariant(
                            variants,
                            "displayId",
                            "displayId"
                          )
                        }
                      )}
                    >
                      {"Name"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__hzag4,
                        {
                          [sty.text__displayId__hzag4Xa4I6]: hasVariant(
                            variants,
                            "displayId",
                            "displayId"
                          )
                        }
                      )}
                    >
                      {":"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox__yftH9,
                        {
                          [sty.freeBox__displayId__yftH9Xa4I6]: hasVariant(
                            variants,
                            "displayId",
                            "displayId"
                          )
                        }
                      )}
                    >
                      {p.renderPlasmicSlot({
                        defaultContents: "N/A",
                        value: args.name,
                        className: classNames(sty.slotTargetName, {
                          [sty.slotTargetName__displayId]: hasVariant(
                            variants,
                            "displayId",
                            "displayId"
                          )
                        })
                      })}
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__kyzOe, {
                      [sty.freeBox__displayId__kyzOeXa4I6]: hasVariant(
                        variants,
                        "displayId",
                        "displayId"
                      )
                    })}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ylFn,
                        {
                          [sty.text__displayId__ylFnxa4I6]: hasVariant(
                            variants,
                            "displayId",
                            "displayId"
                          )
                        }
                      )}
                    >
                      {"Document Number"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__w4Ht3,
                        {
                          [sty.text__displayId__w4Ht3Xa4I6]: hasVariant(
                            variants,
                            "displayId",
                            "displayId"
                          )
                        }
                      )}
                    >
                      {":"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox__xWiVr,
                        {
                          [sty.freeBox__displayId__xWiVrXa4I6]: hasVariant(
                            variants,
                            "displayId",
                            "displayId"
                          )
                        }
                      )}
                    >
                      {p.renderPlasmicSlot({
                        defaultContents: "N/A",
                        value: args.docno,
                        className: classNames(sty.slotTargetDocno, {
                          [sty.slotTargetDocno__displayId]: hasVariant(
                            variants,
                            "displayId",
                            "displayId"
                          )
                        })
                      })}
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__jZShn, {
                      [sty.freeBox__displayId__jZShnXa4I6]: hasVariant(
                        variants,
                        "displayId",
                        "displayId"
                      )
                    })}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__pupwj,
                        {
                          [sty.text__displayId__pupwjxa4I6]: hasVariant(
                            variants,
                            "displayId",
                            "displayId"
                          )
                        }
                      )}
                    >
                      {"Date Of Birth"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___6BTzR,
                        {
                          [sty.text__displayId___6BTzRxa4I6]: hasVariant(
                            variants,
                            "displayId",
                            "displayId"
                          )
                        }
                      )}
                    >
                      {":"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox__jQoPe,
                        {
                          [sty.freeBox__displayId__jQoPeXa4I6]: hasVariant(
                            variants,
                            "displayId",
                            "displayId"
                          )
                        }
                      )}
                    >
                      {p.renderPlasmicSlot({
                        defaultContents: "N/A",
                        value: args.dob,
                        className: classNames(sty.slotTargetDob, {
                          [sty.slotTargetDob__displayId]: hasVariant(
                            variants,
                            "displayId",
                            "displayId"
                          )
                        })
                      })}
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__wpCe, {
                      [sty.freeBox__displayId__wpCeXa4I6]: hasVariant(
                        variants,
                        "displayId",
                        "displayId"
                      )
                    })}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__tufEc,
                        {
                          [sty.text__displayId__tufEcxa4I6]: hasVariant(
                            variants,
                            "displayId",
                            "displayId"
                          )
                        }
                      )}
                    >
                      {"Document Date"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___18Bpw,
                        {
                          [sty.text__displayId___18BpwXa4I6]: hasVariant(
                            variants,
                            "displayId",
                            "displayId"
                          )
                        }
                      )}
                    >
                      {":"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox__dsSsV,
                        {
                          [sty.freeBox__displayId__dsSsVxa4I6]: hasVariant(
                            variants,
                            "displayId",
                            "displayId"
                          )
                        }
                      )}
                    >
                      {p.renderPlasmicSlot({
                        defaultContents: "N/A",
                        value: args.issued,
                        className: classNames(sty.slotTargetIssued, {
                          [sty.slotTargetIssued__displayId]: hasVariant(
                            variants,
                            "displayId",
                            "displayId"
                          )
                        })
                      })}
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__sq35, {
                      [sty.freeBox__displayId__sq35Xa4I6]: hasVariant(
                        variants,
                        "displayId",
                        "displayId"
                      )
                    })}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__irrO7,
                        {
                          [sty.text__displayId__irrO7Xa4I6]: hasVariant(
                            variants,
                            "displayId",
                            "displayId"
                          )
                        }
                      )}
                    >
                      {"Expiry"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__mg0A,
                        {
                          [sty.text__displayId__mg0AXa4I6]: hasVariant(
                            variants,
                            "displayId",
                            "displayId"
                          )
                        }
                      )}
                    >
                      {":"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox__qkNYb,
                        {
                          [sty.freeBox__displayId__qkNYbXa4I6]: hasVariant(
                            variants,
                            "displayId",
                            "displayId"
                          )
                        }
                      )}
                    >
                      {p.renderPlasmicSlot({
                        defaultContents: "N/A",
                        value: args.expiry,
                        className: classNames(sty.slotTargetExpiry, {
                          [sty.slotTargetExpiry__displayId]: hasVariant(
                            variants,
                            "displayId",
                            "displayId"
                          )
                        })
                      })}
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__zG60I, {
                      [sty.freeBox__displayId__zG60IXa4I6]: hasVariant(
                        variants,
                        "displayId",
                        "displayId"
                      )
                    })}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__zzwPb,
                        {
                          [sty.text__displayId__zzwPbxa4I6]: hasVariant(
                            variants,
                            "displayId",
                            "displayId"
                          )
                        }
                      )}
                    >
                      {"Sex"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__nPGq3,
                        {
                          [sty.text__displayId__nPGq3Xa4I6]: hasVariant(
                            variants,
                            "displayId",
                            "displayId"
                          )
                        }
                      )}
                    >
                      {":"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox__rqglL,
                        {
                          [sty.freeBox__displayId__rqglLxa4I6]: hasVariant(
                            variants,
                            "displayId",
                            "displayId"
                          )
                        }
                      )}
                    >
                      {p.renderPlasmicSlot({
                        defaultContents: "N/A",
                        value: args.sex,
                        className: classNames(sty.slotTargetSex, {
                          [sty.slotTargetSex__displayId]: hasVariant(
                            variants,
                            "displayId",
                            "displayId"
                          )
                        })
                      })}
                    </div>
                  </div>
                </div>
              </p.Stack>
            </div>
          </div>
        ) : null}
        {(hasVariant(variants, "notfound", "notfound") ? true : true) ? (
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text___4TZsj,
              {
                [sty.text__notfound___4TZsJvnAI]: hasVariant(
                  variants,
                  "notfound",
                  "notfound"
                )
              }
            )}
          >
            {"No Matching Record Found"}
          </div>
        ) : null}
        {(hasVariant(variants, "displayId", "displayId") ? true : false) ? (
          <button
            data-plasmic-name={"verifyagain"}
            data-plasmic-override={overrides.verifyagain}
            className={classNames(
              projectcss.button,
              projectcss.__wab_text,
              sty.verifyagain,
              {
                [sty.verifyagain__displayId]: hasVariant(
                  variants,
                  "displayId",
                  "displayId"
                )
              }
            )}
          >
            {"Verify Another ID"}
          </button>
        ) : null}
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "applicationForm",
    "walletmount",
    "frame3",
    "graphiteLogo2",
    "tokenno",
    "verifyidbutton",
    "idstack",
    "img",
    "verifyagain"
  ],

  applicationForm: [
    "applicationForm",
    "walletmount",
    "frame3",
    "graphiteLogo2",
    "tokenno",
    "verifyidbutton",
    "idstack",
    "img",
    "verifyagain"
  ],

  walletmount: ["walletmount"],
  frame3: ["frame3", "graphiteLogo2"],
  graphiteLogo2: ["graphiteLogo2"],
  tokenno: ["tokenno"],
  verifyidbutton: ["verifyidbutton"],
  idstack: ["idstack", "img"],
  img: ["img"],
  verifyagain: ["verifyagain"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicVerifyId__ArgProps,
      internalVariantPropNames: PlasmicVerifyId__VariantProps
    });

    return PlasmicVerifyId__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicVerifyId";
  } else {
    func.displayName = `PlasmicVerifyId.${nodeName}`;
  }
  return func;
}

export const PlasmicVerifyId = Object.assign(
  // Top-level PlasmicVerifyId renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    applicationForm: makeNodeComponent("applicationForm"),
    walletmount: makeNodeComponent("walletmount"),
    frame3: makeNodeComponent("frame3"),
    graphiteLogo2: makeNodeComponent("graphiteLogo2"),
    tokenno: makeNodeComponent("tokenno"),
    verifyidbutton: makeNodeComponent("verifyidbutton"),
    idstack: makeNodeComponent("idstack"),
    img: makeNodeComponent("img"),
    verifyagain: makeNodeComponent("verifyagain"),
    // Metadata about props expected for PlasmicVerifyId
    internalVariantProps: PlasmicVerifyId__VariantProps,
    internalArgProps: PlasmicVerifyId__ArgProps
  }
);

export default PlasmicVerifyId;
/* prettier-ignore-end */
